management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
